"""
Library of functions for defining the magnetic fields within the imaging
volume, and receive coil sensitivity within the imaging volume.

To be compatible with the NIBLEs solver, magnetic field functions must 
follow the input format func(t, index, params), where t is the 
simulation time, index is the index value addressing the vector being 
evolved in Experiment.sample_mag, and params is a tuple containing all 
other information required to define the desired applied field. Each 
function should output a magnetic field vector expressed in Cartesian 
co-ordinates as a 3 element NumPy array of float numbers. All fields 
should be defined in the Lab frame, as the NIBLEs solver automatically 
transforms given magnetic fields into the rotating reference frame.

t and index are both generated automatically by the solver, and do not 
need to be defined by an end user. params are generated by the relevant 
sequence element methods when the corresponding field function is 
assigned to a non-Zero function. These params follow standard forms. 
See variable index for details.The parameters given for each function in
this documentation are the elements of the relevant params variable used
by the function.

Receive coil fields use the same parameter format as the magnetic field 
functions (t, index, params), however these functions should instead 
return a single value representing the relative sensitivity of the coil 
for the specified position.
"""

import numpy as np

#~~~~~ B0 Fields ~~~~~#

def ideal_b0(t, index, params):
    """'Calculates' an ideal uniform B0 by simply returning the value of
    Experiment.b0 for a given index.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : array_like
            3-Element array defining applied B0 field as a
            cartesian vector (T).
        params[1] : array_like
            4D array containing field shifts calculated by
            T2star reproduction for each vector (T); 
            Experiment.t2_star_offsets.
        params[2] : array_like
            4D array containing material-specific chemical
            shift for each vector (ppm); Experiment.chem_shift.
        params[3] : dict
            Dictionary containing any keyword arguments provided to
            Experiment using Experiment.b0_set()

    Returns
    -------
    field : array_like
        3-Element array defining applied B0 field as a cartesian vector
        (T).
    """
    field = params[0]
    return field

#~~~~~ B1 Fields ~~~~~#

def rf_sinc(t, index, params):
    """Calculates a sinc shaped RF field in the lab reference frame.

    Can be used to generate a constant amplitude RF pulse by setting
    nLobes = -1 when calling Experiment.rf_pulse().

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : float
            Duration of RF pulse; Experiment.duration
        params[1] : float
            RF field amplitude; Experiment.b1
        params[2] : float
            Carrier frequency of the RF pulse; Experiment.larmor
            + Experiment.del_omega
        params[3] : float
            Phase factor of RF pulse; Experiment.phi
        params[4] : float
            Number of lobes in Sinc pulse waveform; Experiment.n_lobes
        params[5] : dict
            Dictionary containing any keyword arguments provided to
            Experiment.rf_pulse()

    Returns
    -------
    field : array_like
        3-element array defining applied B1 field as a cartesian vector
        (T).
    """

    amp = np.sinc(((params[4]+ 1)/params[0])*(t- params[0]/2))

    # Calculate full RF field
    rf_x = amp* params[1]* np.cos(params[2]*t+ params[3])
    rf_y = -amp* params[1]* np.sin(params[2]*t+ params[3])
    rf_z = 0
    field = np.array([rf_x, rf_y, rf_z], dtype = float)

    return field

def rf_win_sinc_hanning(t, index, params):
    """Calculates a Hanning windowed sinc shaped RF pulse in the lab
    reference frame.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : float
            Duration of RF pulse; Experiment.duration
        params[1] : float
            RF field amplitude; Experiment.b1
        params[2] : float
            Carrier frequency of the RF pulse; Experiment.larmor
            + Experiment.del_omega
        params[3] : float
            Phase factor of RF pulse; Experiment.phi
        params[4] : float
            Number of lobes in Sinc pulse waveform; Experiment.n_lobes
        params[5] : dict
            Dictionary containing any keyword arguments provided to
            Experiment.rf_pulse()

    Returns
    -------
    field : array_like
        3-element array defining applied B1 field as a cartesian vector
        (T).
    """

    amp = (np.sinc(((params[4]+ 1)/params[0])*(t- params[0]/2))
                *(0.5+ 0.5*np.cos(np.pi*(1/params[0])*(t- params[0]/2))))

    # Calculate full RF field
    rf_x = amp* params[1]* np.cos(params[2]*t+ params[3])
    rf_y = -amp* params[1]* np.sin(params[2]*t+ params[3])
    rf_z = 0
    field = np.array([rf_x, rf_y, rf_z], dtype = float)

    return field

def rf_win_sinc_hamming(t, index, params):
    """Calculates a Hamming windowed sinc shaped RF pulse in the lab
    reference frame.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : float
            Duration of RF pulse; Experiment.duration
        params[1] : float
            RF field amplitude; Experiment.b1
        params[2] : float
            Carrier frequency of the RF pulse; Experiment.larmor
            + Experiment.del_omega
        params[3] : float
            Phase factor of RF pulse; Experiment.phi
        params[4] : float
            Number of lobes in Sinc pulse waveform; Experiment.n_lobes
        params[5] : dict
            Dictionary containing any keyword arguments provided to
            Experiment.rf_pulse()

    Returns
    -------
    field : array_like
        3-element array defining applied B1 field as a cartesian vector
        (T).
    """
    amp = (np.sinc(((params[4]+ 1)/params[0])*(t- params[0]/2))
                *(0.54+ 0.46*np.cos(np.pi*(1/params[0])*(t- params[0]/2))))

    # Calculate full RF field
    rf_x = amp* params[1]* np.cos(params[2]*t+ params[3])
    rf_y = -amp* params[1]* np.sin(params[2]*t+ params[3])
    rf_z = 0
    field = np.array([rf_x, rf_y, rf_z], dtype = float)

    return field


#~~~~~ Gradient Fields ~~~~~#

def grad_ideal_square(t, index, params):
    """Calculates an ideal square gradient waveform as a function of
    position within the imaging volume.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : array_like
            4D array containing positions of all vectors;
            Experiment.m_position
        params[1] : array_like
            Maximum amplitude of gradient, expressed as a 
            3-element NumPy array; Experiment.grad_amp
        params[2] : array_like
            Dimensions of the imaging volume in metric; 
            Experiment.size_metric
        params[3] : float
            Duration of gradient; Experiment.duration
        params[4] : float
            Rise time of gradient waveform; Experiment.rise_time
        params[5] : dict
            Dictionary containing any keyword arguments provided to any
            of the gradient methods in Experiment (eg.
            Experiment.gradient())

    Returns
    -------
    b_grad : array_like
        3-element array defining applied gradient field as a cartesian
        vector (T).
    """

    # Calculate max gradient amplitude at vector position
    position = params[0][index]
    position_amp = params[1]*(position- params[2]/2)

    b_grad = np.array([0, 0, np.sum(position_amp)])

    return b_grad

def grad_ideal_trap(t, index, params):
    """Calculates an ideal trapezoidal gradient waveform as a function
    of position within the imaging volume.

    Gradient linearly increases from 0 to max amplitude over 
    Experiment.rise_time at the beginning of the gradient, remains
    constant until it reaches Experiment.duration- Experiment.rise_time,
    and finally linearly decreases back to zero.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : array_like
            4D array containing positions of all vectors;
            Experiment.m_position
        params[1] : array_like
            Maximum amplitude of gradient, expressed as a 
            3-element NumPy array; Experiment.grad_amp
        params[2] : array_like
            Dimensions of the imaging volume in metric; 
            Experiment.size_metric
        params[3] : float
            Duration of gradient; Experiment.duration
        params[4] : float
            Rise time of gradient waveform; Experiment.rise_time
        params[5] : dict
            Dictionary containing any keyword arguments provided to any
            of the gradient methods in Experiment (eg.
            Experiment.gradient())

    Returns
    -------
    b_grad : array_like
        3-element array defining applied gradient field as a cartesian
        vector (T).
    """
    # Calculate max gradient amplitude at vector position
    position = params[0][index]
    position_amp = params[1]*(position- params[2]/2)

    # Calculate slope of gradient
    slew_rate = position_amp/params[4]

    # Identify where in the trapezoid simulation is happeneing, then
    # calculate appropriate field
    if t < params[4]:
        amp = slew_rate*t
    elif params[4] <= t <= (params[3]- params[4]):
        amp = position_amp
    elif t > (params[3]- params[4]):
        amp = position_amp - slew_rate*(t- (params[3]- params[4]))

    b_grad = np.array([0, 0, np.sum(amp)])

    return b_grad

#~~~~~ Rx Fields ~~~~~#

def rx_uniform(t, index, params):
    """'Calculates' a uniform receive coil sensitivity across the entire
    imaging volume.

    Parameters
    ----------
    t : float
        Simulation time. Produced by solver and should not be defined by
        end user.
    index : array_like
        List indicating the index in Experiment.sample_mag corresponding
        to the vector being simulated
    params : tuple
        Parameter tuple where each element is the following:
        params[0] : array_like
            4D array containing positions of all vectors;
            Experiment.m_position
        params[1] : array_like
            Dimensions of the imaging volume in metric; 
            Experiment.size_metric
        params[2] : array_like
            Dimensions of the imaging volume in pixels; 
            Experiment.size_pixels
        params[3] : dict
            Dictionary containing any keyword arguments provided to
            Experiment using Experiment.rx_set()

    Returns
    -------
    rx_sensitivity : float
        Floating point number indicating the relative sensitivity of the
        RX coil at the specified position.
    """
    rx_sensitivity = 1
    return rx_sensitivity

