import numpy as np

# Functions for defining the magnetic fields within the imaging volume, and receive coil sensitivity 
# within the imaging volume.
#
# To be compatible with the NIBLEs solver, magnetic field functions must follow the input format 
# func(t, index, Params), where t is the simulation time, index is the index value addressing the 
# vector being evolved in Experiment.M, and Params is a tuple containing all other information 
# required to define the desired applied field. Each function should output a magnetic field vector 
# expressed in Cartesian co-ordinates as a 3 element NumPy array of float numbers. All fields should 
# be defined in the Lab frame, as the NIBLEs solver automatically transforms given magnetic fields 
# into the rotating reference frame.
#
# t and index are both generated automatically by the solver, and do not need to be defined by an 
# end user. Params are generated by the relevant sequence element methods when the corresponding 
# field function is assigned to a non-Zero function. These Params follow standard forms. See 
# variable index for details.The parameters given for each function in this documentation are the
# elements of the relevant Params variable used by the function.
#
# Receive coil fields use the same parameter format as the magnetic field functions (t, index, Params), 
# however these functions should instead return a single value representing the relative sensitivity of 
# the coil for the specified position.
#
# Original version of this code designed and written by John Adams (jadam33@uwo.ca)
#
# This code is published under a GNU General Public License version 3 License. Anyone using this code 
# must give attribution to the original author (John Adams), and must make any derivative code built 
# using this code available under the same licensing terms.


#~~~~~ Version History ~~~~~#
# 1.0  Public Release - July 1 2026 - John Adams


#~~~~~ B0 Fields ~~~~~#

def IdealB0(t, index, Params):
    """
    Function 'calculates' an ideal uniform B0 by simply returning the value of Experiment.Blab +
    for a given index.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector 
    being simulated
    Params = Parameter tuple where each element is the following:
        Params[0] = Numpy 4D array containing nominal B0 field at the location of the vector being 
            evolved (T); Experiment.BLab
        Params[1] = Numpy 4D array containing field shifts calculated by T2star reproduction for 
            each vector (T); Experiment.t2starOffsets
        Params[2] = Numpy 4D array containing material-specific chemical shift for each vector (ppm); 
        Experiment.chemShift

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    return Params[0]

#~~~~~ B1 Fields ~~~~~#

def RF_Sinc(t, index, Params):
    """
    Function calculates an ideal Sinc RF waveform in the lab reference frame. Can be used to 
    generate a constant amplitude RF pulse by setting nLobes = -1

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector 
    being simulated
    Params = Parameter tuple where each element is the following:
		Params[0] = Duration of RF pulse; Experiment.Duration
		Params[1] = RF field amplitude expressed as a 3 element Numpy Aray; Experiment.B1
		Params[2] = Carrier frequency of the RF pulse; Experiment.Larmor+ Experiment.dOmega
		Params[3] = Phase factor of RF pulse; Experiment.Phi
		Params[4] = Number of lobes in Sinc pulse waveform; Experiment.nLobes

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate RF waveform

    Amp = np.sinc(((Params[4]+ 1)/Params[0])*(t- Params[0]/2))

    # Calculate full RF field
    RFx = Amp* Params[1]* np.cos(Params[2]*t+ Params[3])
    RFy = -Amp* Params[1]* np.sin(Params[2]*t+ Params[3])
    RFz = 0

    return np.array([RFx, RFy, RFz], dtype = float)

def RF_WinSinc_Hanning(t, index, Params):
    """
    Function calculates a Hanning windowed RF waveform in the lab reference frame.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector 
    being simulated
    Params = Parameter tuple where each element is the following:
		Params[0] = Duration of RF pulse; Experiment.Duration
		Params[1] = RF field amplitude expressed as a 3 element Numpy Aray; Experiment.B1
		Params[2] = Carrier frequency of the RF pulse; Experiment.Larmor+ Experiment.dOmega
		Params[3] = Phase factor of RF pulse; Experiment.Phi
		Params[4] = Number of lobes in Sinc pulse waveform; Experiment.nLobes

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate RF waveform
    Amp = np.sinc(((Params[4]+ 1)/Params[0])*(t- Params[0]/2))* ...
    (0.5+ 0.5*np.cos(np.pi*(1/Params[0])*(t- Params[0]/2)))

    # Calculate full RF field
    RFx = Amp* Params[1]* np.cos(Params[2]*t+ Params[3])
    RFy = -Amp* Params[1]* np.sin(Params[2]*t+ Params[3])
    RFz = 0

    return np.array([RFx, RFy, RFz], dtype = float)

def RF_WinSinc_Hamming(t, index, Params):
    """
    Function calculates a Hamming windowed RF waveform in the lab reference frame.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector 
    being simulated
    Params = Parameter tuple where each element is the following:
		Params[0] = Duration of RF pulse; Experiment.Duration
		Params[1] = RF field amplitude expressed as a 3 element Numpy Aray; Experiment.B1
		Params[2] = Carrier frequency of the RF pulse; Experiment.Larmor+ Experiment.dOmega
		Params[3] = Phase factor of RF pulse; Experiment.Phi
		Params[4] = Number of lobes in Sinc pulse waveform; Experiment.nLobes

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate RF waveform
    Amp = np.sinc(((Params[4]+ 1)/Params[0])*(t- Params[0]/2))* ...
    (0.54+ 0.46*np.cos(np.pi*(1/Params[0])*(t- Params[0]/2)))

    # Calculate full RF field
    RFx = Amp* Params[1]* np.cos(Params[2]*t+ Params[3])
    RFy = -Amp* Params[1]* np.sin(Params[2]*t+ Params[3])
    RFz = 0

    return np.array([RFx, RFy, RFz], dtype = float)


#~~~~~ Gradient Fields ~~~~~#

def Grad_IdealSquare(t, index, Params):
    """
    Function calculates an ideal square gradient waveform as a function of position 
    within the imaging volume.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector 
    being simulated
    Params = Parameter tuple where each element is the following:
	    Params[0] = Numpy 4D array containing positions of all vectors; Experiment.MPosition
	    Params[1] = Maximum amplitude of gradient, expressed as a 3 element NumPy array;
            Experiment.gradAmp
	    Params[2] = Dimensions of the imaging volume in metric; Experiment.sizeMetric

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate max gradient amplitude at vector position
    Position = Params[0][index]
    positionalAmplitude = Params[1]*(Position- Params[2]/2)

    Bgrad = np.array([0, 0, np.sum(positionalAmplitude)])        

    return Bgrad

def Grad_IdealTrapezoid(t, index, Params):
    """
    Function calculates an ideal trapezoid gradient as a function of position within the imaging volume, 
    where the gradient linearly increases from 0 to max amplitude over Experiment.riseTime at the 
    beginning of the gradient, remains constant until it reaches Experiment.Duration- Experiment.riseTime, 
    and finally linearly decreases back to zero.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector being simulated
    Params = Parameter tuple where each element is the following:
        Params[0] = Numpy 4D array containing positions of all vectors; Experiment.MPosition
        Params[1] = Maximum amplitude of gradient, expressed as a 3 element NumPy array; Experiment.gradAmp
        Params[2] = Dimensions of the imaging volume in metric; Experiment.sizeMetric
        Params[3] = Duration of gradient waveform; Experiment.Duration
        Params[4] = Rise time of gradient; Experiment.riseTime

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate max gradient amplitude at vector position
    Position = Params[0][index]
    positionalAmplitude = Params[1]*(Position- Params[2]/2)

    # Calculate slope of gradient
    slewRate = positionalAmplitude/Params[4]

    # Identify where in the trapezoid simulation is happeneing, then calculate appropriate field
    if t < Params[4]:
        Amp = slewRate*t
    elif Params[4] <= t <= (Params[3]- Params[4]):
        Amp = positionalAmplitude
    elif t > (Params[3]- Params[4]):
        Amp = positionalAmplitude - slewRate*(t- (Params[3]- Params[4]))

    Bgrad = np.array([0, 0, np.sum(Amp)])

    return Bgrad

def Grad_IdealRampUp(t, index, Params):
    """
    Function calculates an ideal gradient ramp as a function of position within the imaging volume, 
    where the gradient linearly increases from 0 to max amplitude over Experiment.Duration

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector being simulated
    Params = Parameter tuple where each element is the following:
        Params[0] = Numpy 4D array containing positions of all vectors; Experiment.MPosition
        Params[1] = Maximum amplitude of gradient, expressed as a 3 element NumPy array; Experiment.gradAmp
        Params[2] = Dimensions of the imaging volume in metric; Experiment.sizeMetric
        Params[3] = Duration of gradient waveform; Experiment.Duration

    Returns:
    3-element Numpy array containing the x-, y-, and z- components of calculated field
    """
    # Calculate max gradient amplitude at vector position
    Position = Params[0][index]
    positionalAmplitude = Params[1]*(Position- Params[2]/2)

    # Calculate slope of gradient
    slewRate = positionalAmplitude/Params[3]

    # Calculate gradient amplitude
    Amp = slewRate*t
    Bgrad = np.array([0, 0, np.sum(Amp)])

    return Bgrad

#~~~~~ Rx Fields ~~~~~#

def RxUniform(t, index, Params):
    """
    Function returns a receive coil sensitivity of 1 across the entire imaging volume.

    Parameters:
    t = Time from beginning of sequence element (s)
    index = 4-element list indicating the index in Experiment.M corresponding to the vector being simulated
    Params = Unused placeholder variable

    Returns:
    Floating point number denoting the relative sensitivity of the receive coil
    """
    return 1

