import numpy as np

# Functions for defining noise variance in MR readouts. All functions should return
# a complex array containing real and imaginary noise values with same dimensionality
# as Exp.cReadout as generated by Exp.Acquire()
#
# As inputs, each function accepts a tuple named noiseParams for user control of 
# noise behaviour, the signal noise will be added to, and 8 variables calculated 
# automatically within Experiment() from given sample and magnet parameters.
#
# Original version of this code designed and written by John Adams (jadam33@uwo.ca)
#
# This code is published under a GNU General Public License version 3 License. Anyone using this code 
# must give attribution to the original author (John Adams), and must make any derivative code built 
# using this code available under the same licensing terms.


#~~~~~ Version History ~~~~~#
# 1.0  Public Release - July 1 2026 - John Adams

def KnownKSpaceSNR(noiseParams, signal, shape, B0, nAcq, gamma, rng):

    """
    Function that adds noise to acquired signal to generate a known SNR.

    Parameters:
    noiseParams = One element tuple containing the desired k-space SNR
    signal = Numpy array containing k-space data
    shape = signal.shape()
    B0 = Nominal B0 field strength. Unused in calculations.
    nAcq = Number of acquisitions for noise scaling. Unused in calculations.
    gamma = Gyromagnetic ratio of nucleus in rad/T. unused in calculations.
    rng = Instance of numpy.random.default_rng()

    Returns: 
    Numpy array of random complex noise, with the same dimensions as signal
    """

    noiseDeviation = np.max(np.abs(signal))/noiseParams

    noiseMatrix = rng.normal(0, noiseDeviation, shape)+ 1.0j*rng.normal(0, noiseDeviation, shape)

    return noiseMatrix

def KnownImageSpaceSNR(noiseParams, image, shape, B0, nAcq, gamma, rng):

    """
    Function that adds noise to existing image to generate a known SNR relative to the image intensity 
    of a given region.

    Parameters:
    noiseParams = Parameter tuple where each element is the following:
        Param[0] = Desired SNR for image
        Param[1] = Lower X bound for signal region 
        Param[2] = Upper X bound for signal region 
        Param[3] = Lower Y bound for signal region 
        Param[4] = Upper Y bound for signal region 
    image = Numpy array containing image intensity values
    shape = image.shape()
    B0 = Nominal B0 field strength. Unused in calculations.
    nAcq = Number of acquisitions for noise scaling. Unused in calculations.
    gamma = Gyromagnetic ratio of nucleus in rad/T. Unused in calculations.
    rng = Instance of numpy.random.default_rng()

    Returns: 
    Numpy array of random complex noise, with the same dimensions as image
    """

    averageSignal = np.average(image[noiseParams[1]:noiseParams[2], noiseParams[3]:noiseParams[4]])
    noiseDeviation = averageSignal/noiseParams[0]

    noiseMatrix = rng.normal(0, noiseDeviation, shape)+ 1.0j*rng.normal(0, noiseDeviation, shape)

    return abs(noiseMatrix)

def KnownNoiseVariance(noiseParams, signal, shape, B0, nAcq, gamma, rng):

    """
    Function that adds noise to acquired data using a known noise variance. Intended to be used in multi-
    image sequences where noise is calculated based on first image, then that noise variance can be 
    propagated through subsequent images to preserve changes in SNR across a sequence.

    Parameters:
    noiseParams = One element tuple containing the desired k-space SNR
    data = Numpy array containing k-space data. Unused in calculations.
    shape = signal.shape()
    B0 = Nominal B0 field strength. Unused in calculations.
    nAcq = Number of acquisitions for noise scaling.
    gamma = Gyromagnetic ratio of nucleus in rad/T. Unused in calculations.
    rng = Instance of numpy.random.default_rng()

    Returns: 
    Numpy array of random complex noise, with the same dimensions as data
    """

    noiseVariance = noiseParams

    noiseOut = np.zeros(shape, dtype = 'complex')

    for j in range(nAcq):
        noiseMatrix = rng.normal(0, noiseVariance, shape)+ 1.0j*rng.normal(0, noiseVariance, shape)
        noiseOut += noiseMatrix

    return noiseOut/nAcq

