"""
Library of functions for defining noise variance in MR readouts. All
functions should return a complex array containing real and imaginary
noise values with same dimensionality as Exp.readout as generated by
Experiment.acquire()

As inputs, each function accepts a tuple named noise_params for user 
control of noise behaviour, the signal noise will be added to, and 
variables calculated automatically within Experiment() from given 
sample and magnet parameters.
"""

import numpy as np

def known_kspace_snr(noise_params, signal, b0, n_acq, GAMMA, RNG):
    """Calculates a noise matrix that can be added to
    complex k-space signal to generate a known SNR.

    Parameters
    ----------
    noise_params : float
        Desired k-space SNR.
    signal : array_like
        Numpy array containing k-space data.
    b0 : array_like
        Total magnetic field in the lab reference frame. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    n_acq : int
        Number of acquisitions for noise scaling. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    GAMMA : float
        Gyromagnetic ratio of nucleus in rad/T. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    RNG : object
        Instance of numpy.random.default_RNG().

    Returns
    -------
    noise_mat : array_like
        Numpy array of random complex noise, with the same dimensions
        as signal.
    """

    shape = signal.shape()
    noise_dev = np.max(np.abs(signal))/noise_params

    noise_mat = (RNG.normal(0, noise_dev, shape)
                 + 1.0j*RNG.normal(0, noise_dev, shape))

    return noise_mat

def known_image_snr(noise_params, image, b0, n_acq, GAMMA, RNG):
    """Calculates a noise matrix that can be added to a 2D image to
    generate a known SNR relative to the image intensity of a given
    region.

    Parameters
    ----------
    noise_params : tuple
        Parameter tuple where each element is the following:
        Param[0] = Desired SNR for image
        Param[1] = Lower X bound for signal region 
        Param[2] = Upper X bound for signal region 
        Param[3] = Lower Y bound for signal region 
        Param[4] = Upper Y bound for signal region 
    image : array_like
        Numpy array containing image intensity values.
    b0 : array_like
        Total magnetic field in the lab reference frame. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    n_acq : int
        Number of acquisitions for noise scaling. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    GAMMA : float
        Gyromagnetic ratio of nucleus in rad/T. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    RNG : object
        Instance of numpy.random.default_RNG().

    Returns
    -------
    noise_mat : array_like
        Numpy array of random real noise, with the same dimensions
        as image.
    """

    shape = image.shape()
    avg_signal = np.average(image[noise_params[1]:noise_params[2],
                                  noise_params[3]:noise_params[4]])
    noise_dev = avg_signal/noise_params[0]

    noise_mat = (RNG.normal(0, noise_dev, shape)
                 + 1.0j*RNG.normal(0, noise_dev, shape))

    return abs(noise_mat)

def known_noise_variance(noise_params, signal, b0, n_acq, GAMMA, RNG):
    """Calculates a noise matrix that can be added to k-space signal
    using a known noise variance.

    Designed to be used in multi-image sequences where noise 
    is calculated based on first image, then that noise variance can be
    propagated through subsequent images to preserve changes in SNR 
    across a sequence.

    Parameters
    ----------
    noise_params : float
        Desired k-space SNR.
    image : array_like
        Numpy array containing image intensity values.
    b0 : array_like
        Total magnetic field in the lab reference frame. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    n_acq : int
        Number of acquisitions for noise scaling.
    GAMMA : float
        Gyromagnetic ratio of nucleus in rad/T. Not used in
        calculations, but present as input to maintain standard format
        for noise functions.
    RNG : object
        Instance of numpy.random.default_RNG().

    Returns
    -------
    noise_mat : array_like
        Numpy array of random real noise, with the same dimensions
        as image.
    """
    shape = signal.shape()
    noise_var = noise_params
    noise_mat = np.zeros(shape, dtype = 'complex')

    for j in range(n_acq):
        noise = (RNG.normal(0, noise_var, shape)
                 + 1.0j*RNG.normal(0, noise_var, shape))
        noise_mat += noise

    return noise_mat/n_acq
